export const webFrozenMap: Record<string, string> = {
  '': 'tgs_home_v7.html',
  'about': 'tgs_about_v4.html',
  'contact': 'tgs_contact_v4.html',
  'how-it-works': 'tgs_how_it_works_v4 (2).html',
  'legal': 'tgs_legal_v5.html',
  'list-your-venue': 'tgs_list_your_venue_v4.html',
  'the-wellness-edit': 'tgs_wellness_edit_v2 (1).html',
  'venues': 'tgs_venues_v3.html',
  'venues-legacy': 'tgs_venues.html',
  'wellness-experiences': 'tgs_wellness_experiences_v6.html',
};

export const portalFrozenMap: Record<string, string> = {
  '': 'TGS Internal Portal Home Page V2.html',
  'tgs_internal_portal_-_retreat_venue_overview_tab_v3': 'TGS_Internal_Portal_-_Retreat_Venue_Overview_Tab_V3.html',
  'tgs_internal_portal_-_wellness_venue_overview_v3': 'TGS_Internal_Portal_-_Wellness_Venue_Overview_V3.html',
  'tgs-internal-portal-analytics': 'TGS Internal Portal Analytics.html',
  'tgs-internal-portal---bookings-dashboard': 'TGS Internal Portal - Bookings Dashboard.html',
  'tgs-internal-portal-enquiries-dashboard': 'TGS Internal Portal Enquiries Dashboard.html',
  'tgs-internal-portal---individual-retreat-host-profile': 'TGS Internal Portal - Individual Retreat Host Profile.html',
  'tgs-internal-portal---individual-venue-owner-profile': 'TGS Internal Portal - Individual Venue Owner Profile.html',
  'tgs-internal-portal-payments': 'TGS Internal Portal Payments.html',
  'tgs-internal-portal---retreat-host-general-dashboard': 'TGS Internal Portal - Retreat Host General Dashboard.html',
  'tgs-internal-portal---retreat-venue-accommodation-tab-v2': 'TGS Internal Portal - Retreat Venue Accommodation Tab V2.html',
  'tgs-internal-portal---retreat-venue-amenities-tab-v2': 'TGS Internal Portal - Retreat Venue Amenities Tab V2.html',
  'tgs-internal-portal---retreat-venue-bookings-tab-v2': 'TGS Internal Portal - Retreat Venue Bookings Tab V2.html',
  'tgs-internal-portal---retreat-venue-facilities-tab-v2': 'TGS Internal Portal - Retreat Venue Facilities Tab V2.html',
  'tgs-internal-portal---retreat-venue-media-tab-v2': 'TGS Internal Portal - Retreat Venue Media Tab V2.html',
  'tgs-internal-portal---retreat-venue-owner-manager-tab-v2': 'TGS Internal Portal - Retreat Venue Owner Manager Tab V2.html',
  'tgs-internal-portal---retreat-venue-pricing-booking-v2': 'TGS Internal Portal - Retreat Venue Pricing Booking V2.html',
  'tgs-internal-portal---retreat-venue-tgs-internal-v2': 'TGS Internal Portal - Retreat Venue TGS Internal V2.html',
  'tgs-internal-portal---retreat-venue-wellness-facilities-v2': 'TGS Internal Portal - Retreat Venue Wellness Facilities V2.html',
  'tgs-internal-portal---retreat-venue-wellness-services-v2': 'TGS Internal Portal - Retreat Venue Wellness Services V2.html',
  'tgs-internal-portal-sanctum-journal': 'TGS Internal Portal Sanctum Journal.html',
  'tgs-internal-portal-settings': 'TGS Internal Portal Settings.html',
  'tgs-internal-portal-subscriptions': 'TGS Internal Portal Subscriptions.html',
  'tgs-internal-portal-the-wellness-edit': 'TGS Internal Portal The Wellness Edit.html',
  'tgs-internal-portal-users': 'TGS Internal Portal Users.html',
  'tgs-internal-portal-venue-owners-general-dashboard': 'TGS Internal Portal Venue Owners General Dashboard.html',
  'tgs-internal-portal-venues-page-v2': 'TGS Internal Portal Venues Page V2.html',
  'tgs-internal-portal---wellness-guest-general-dashboard': 'TGS Internal Portal - Wellness Guest General Dashboard.html',
  'tgs-internal-portal---wellness-guest-individual-profile': 'TGS Internal Portal - Wellness Guest Individual Profile.html',
  'tgs-internal-portal---wellness-venue-accommodation-tab-v2': 'TGS Internal Portal - Wellness Venue Accommodation Tab V2.html',
  'tgs-internal-portal---wellness-venue-amenities-v2': 'TGS Internal Portal - Wellness Venue Amenities V2.html',
  'tgs-internal-portal---wellness-venue-booking-pricing-tab-v2': 'TGS Internal Portal - Wellness Venue Booking Pricing Tab V2.html',
  'tgs-internal-portal---wellness-venue-bookings-v2': 'TGS Internal Portal - Wellness Venue Bookings V2.html',
  'tgs-internal-portal---wellness-venue-facilities-tab-v2': 'TGS Internal Portal - Wellness Venue Facilities Tab V2.html',
  'tgs-internal-portal---wellness-venue-media-v2': 'TGS Internal Portal - Wellness Venue Media V2.html',
  'tgs-internal-portal---wellness-venue-owner-manager-tab-v2': 'TGS Internal Portal - Wellness Venue Owner Manager Tab V2.html',
  'tgs-internal-portal---wellness-venue-services-v2': 'TGS Internal Portal - Wellness Venue Services V2.html',
  'tgs-internal-portal---wellness-venue-tgs-internal-v2': 'TGS Internal Portal - Wellness Venue TGS Internal V2.html',
};

export function toFrozenSrc(section: "web-pages" | "portal-pages", fileName: string): string {
  return `/frozen/${section}/${encodeURIComponent(fileName)}`;
}
