export const tgsRoutes = {
  home: "/global-santcum/web",
  book: "/global-santcum/book",
  venues: "/global-santcum/venues",
  retreatVenues: "/global-santcum/retreat-venues",
  wellnessVenues: "/global-santcum/wellness-venues",
  wellnessExperiences: "/global-santcum/wellness-experiences",
  about: "/global-santcum/about",
  ourStory: "/global-santcum/our-story",
  howItWorks: "/global-santcum/how-it-works",
  wellnessEdit: "/global-santcum/the-wellness-edit",
  sanctumJournal: "/global-santcum/sanctum-journal",
  contact: "/global-santcum/contact",
  press: "/global-santcum/contact#press-media",
  listYourVenue: "/global-santcum/list-your-venue",
  hostRetreat: "/global-santcum/host-a-retreat",
  legal: "/global-santcum/legal",
  terms: "/global-santcum/terms-and-conditions",
  privacy: "/global-santcum/privacy-policy",
  cookies: "/global-santcum/cookies-policy",
};
